#s3.access_key=obj-sdk
#s3.secret_key=UhokvGNu3ZZOza68xsFRUjQj4x0cyWtRFM+oMStm
#s3.access_key=emily
#s3.secret_key=KIf3P/lkIgZ0hCa98Vu2cxDIVVzZeu0E3RbzRgtO
#s3.endpoint=http://10.246.151.135:9020
# s3.region=us-west-2
disableSmartClient=false


#s3.endpoint=http://s3.ap-south-1.amazonaws.com
#s3.access_key=AKIATVANNG4ISQBWQIAR
#s3.secret_key=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

#s3.iam_user=true

s3.endpoint=http://10.246.155.71:9020
s3.access_key=obju1
s3.secret_key=gxIvoTcHl6G81OFuLN0D8yGIo33vMIy5MZfs6/Fu